version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  build-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
workflows:
  just-build-it:
    jobs:
      - node/run:
          npm-run: build